#!/usr/bin/env python3
"""
audit-to-memory.py — convert audit findings to draft memory entries

Reads the latest `.scratch/<audit>/SYNTHESIS.md` table (or any markdown table
with the same shape), extracts items that are still `Partial` or `Absent`,
and writes draft memory entries in the frontmatter format the harness
memory system expects.

The script NEVER writes to `MEMORY.md` directly — that is an operator-mediate
step (preserves the autonomy invariant: the human reviews, rewords, and merges
into the persistent index). It writes to a single draft file the operator
opens in a follow-up step.

Usage:
    # Default: scans the most recent .scratch/*/SYNTHESIS.md
    python3 scripts/audit-to-memory.py

    # Explicit audit slug
    python3 scripts/audit-to-memory.py --audit harness-loop-audit-2026-06-12

    # Show what would be drafted without writing
    python3 scripts/audit-to-memory.py --dry-run

    # Filter: only Core-weight items
    python3 scripts/audit-to-memory.py --weight Core

Output:
    Writes to ~/.claude/projects/<project>/memory/draft-audit-findings.md
    (overwrites any prior draft — single canonical draft at a time)

The script is read-only with respect to MEMORY.md, scripts/, and the rest
of the repo. It only writes to the draft file. No subprocess calls, no
network. Pure markdown table parser.
"""

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# Repo root = grandparent of this file (scripts/audit-to-memory.py)
REPO_ROOT = Path(__file__).resolve().parent.parent

# Memory root (per CONTEXT.md and the existing memory format)
MEMORY_ROOT = Path.home() / ".claude" / "projects" / "-Users-kobig-Codes-Personals-kbg-harness" / "memory"
DRAFT_PATH = MEMORY_ROOT / "draft-audit-findings.md"

# Table row pattern — matches the SYNTHESIS.md 50-row table.
# Columns: | # | ID | Title | Status | Weight | Category | Layer |
# Status is the field we filter on; ID becomes the memory slug; Title
# becomes the one-line description; Weight+Category flow to the frontmatter.
ROW_RE = re.compile(
    r"^\|\s*(?P<num>\d+)\s*\|"
    r"\s*(?P<id>[\w\-]+)\s*\|"
    r"\s*(?P<title>[^|]+?)\s*\|"
    r"\s*\*\*(?P<status>Present|Partial|Absent|Vendor-only|Failed-verify)\*\*\s*\|"
    r"\s*(?P<weight>Core|Important|Nice-to-have)\s*\|"
    r"\s*(?P<category>[\w\-]+)\s*\|"
    r"\s*(?P<layer>[\w\-/]+)\s*\|"
    r"\s*$"
)


def find_latest_synthesis() -> Path | None:
    """Return the path to the most recent .scratch/*/SYNTHESIS.md, if any."""
    scratch = REPO_ROOT / ".scratch"
    if not scratch.exists():
        return None
    candidates = sorted(scratch.glob("*/SYNTHESIS.md"), key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0] if candidates else None


def parse_synthesis(path: Path) -> list[dict]:
    """Parse the 50-row SYNTHESIS table. Returns a list of dicts."""
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = ROW_RE.match(line.strip())
        if m:
            rows.append(m.groupdict())
    return rows


def render_draft(rows: list[dict], source: Path) -> str:
    """Render the draft memory file in the harness's frontmatter format."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    n = len(rows)
    header = f"""---
name: draft-audit-findings
description: "DRAFT — open, review, and either (a) move individual sections to MEMORY.md as separate slugged memories or (b) discard. Never auto-promoted. Generated by scripts/audit-to-memory.py from {source.name} on {now}."
metadata:
  type: project
  status: draft
  source_audit: {source.parent.name}
  generated_at: {now}
  item_count: {n}
---

# Audit findings — DRAFT (operator review required)

> This file is a **draft** generated by `scripts/audit-to-memory.py`. It is
> not part of the persistent memory. Open it, read it, and either:
> 1. **Promote** an item to a real `MEMORY.md` entry (write a dedicated
>    `<slug>.md` with proper frontmatter, add a 1-line pointer in
>    `MEMORY.md`).
> 2. **Discard** an item (it was noise, rediscovery, or already captured).
> 3. **Defer** an item (write a one-liner to a `deferred-` file for a
>    future audit to revisit).
>
> Do not let the draft sit forever — it will go stale the next time
> the script runs.

Source: `{source}` ({n} items, filtered to `Partial` / `Absent` /
`Failed-verify`).

Each item below is a *draft* memory entry. Reword before promoting;
the script captures what the audit said, not what you should remember.

"""
    sections = []
    for r in rows:
        slug = r["id"]
        title = r["title"].strip()
        weight = r["weight"]
        cat = r["category"]
        layer = r["layer"]
        status = r["status"]
        body = f"""## {slug} ({weight} · {cat} · {layer}) — {status}

**Title (from audit):** {title}

**Drafted frontmatter (review + reword before promoting):**

```yaml
---
name: {slug}
description: "<one-line summary — reword to capture WHY, not just WHAT>"
metadata:
  type: project
  source_audit: {source.parent.name}
  weight: {weight}
  status_at_audit: {status}
---
```

**Drafted body:**

> {title}.
> Status as of {now}: {status}. Weight: {weight}. Category: {cat}. Layer: {layer}.
>
> **Why this matters:** (FILL IN — the audit only states the absence; the
> lesson is what you should do differently next time. If you can't fill
> this in, the item probably isn't worth promoting.)
>
> **How to apply:** (FILL IN — a concrete rule, not a vague principle. The
> existing memory files in this directory show the shape.)

**Action:** Promote · Discard · Defer

"""
        sections.append(body)
    return header + "\n".join(sections)


def main() -> int:
    p = argparse.ArgumentParser(
        description="Convert audit findings to a draft memory file (operator reviews, never auto-promoted)."
    )
    p.add_argument(
        "--audit",
        type=str,
        default=None,
        help="Audit slug under .scratch/ (default: most recent)",
    )
    p.add_argument(
        "--weight",
        type=str,
        choices=["Core", "Important", "Nice-to-have", "all"],
        default="all",
        help="Filter by audit weight (default: all)",
    )
    p.add_argument(
        "--include-present",
        action="store_true",
        help="Also include Present items (default: omit — they're shipped, nothing to learn)",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print draft to stdout instead of writing",
    )
    p.add_argument(
        "--output",
        "-o",
        type=str,
        default=None,
        help="Override output path (default: MEMORY_ROOT/draft-audit-findings.md)",
    )
    args = p.parse_args()

    if args.audit:
        source = REPO_ROOT / ".scratch" / args.audit / "SYNTHESIS.md"
        if not source.exists():
            print(f"ERROR: {source} not found", file=sys.stderr)
            return 2
    else:
        source = find_latest_synthesis()
        if source is None:
            print("ERROR: no .scratch/*/SYNTHESIS.md found", file=sys.stderr)
            return 2
        print(f"Using latest SYNTHESIS: {source}", file=sys.stderr)

    rows = parse_synthesis(source)
    if not rows:
        print(f"ERROR: no rows parsed from {source} (table format may have changed)", file=sys.stderr)
        return 3

    # Filter
    interesting = {"Partial", "Absent", "Failed-verify"}
    if args.include_present:
        interesting.add("Present")
    rows = [r for r in rows if r["status"] in interesting]
    if args.weight != "all":
        rows = [r for r in rows if r["weight"] == args.weight]
    rows.sort(key=lambda r: int(r["num"]))

    if not rows:
        print("No items match filter — nothing to draft.", file=sys.stderr)
        return 0

    draft = render_draft(rows, source)

    if args.dry_run:
        sys.stdout.write(draft)
        return 0

    output = Path(args.output) if args.output else DRAFT_PATH
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(draft, encoding="utf-8")
    print(f"Wrote {len(rows)} draft items to {output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
