#!/usr/bin/env bash
# 50. mattpocock-skills integration refs — kbg routes to matt's fleet by
# namespaced name with no resolver, so an upstream rename lands silently
# (proven live: writing-great-skills → writing-for-agents in matt v1.2.0 left
# dead refs in CLAUDE.md + docs/skill-authoring-conventions.md, caught
# 2026-08-10 by the survey that built this check — checks 25/37 structurally
# could not see it: 25 reads only agents' `skills:` YAML arrays, 37 only
# `mh:` tokens). Four sub-checks against the INSTALLED mattpocock cache:
#   A (WARN) every `mattpocock-skills:<name>` token in live surfaces resolves
#     to an installed skill. Bucket prefixes are stripped and resolution is
#     depth-agnostic (find, not skills/<bucket>/<name> paths) — upstream's
#     pending flatten-skills-tree branch removes bucket nesting entirely.
#   B (WARN) a line asserting `disable-model-invocation: true` about a
#     `mattpocock-skills:<name>` must match the target's real frontmatter
#     (upstream flips a flag → kbg's routing prose goes stale invisibly).
#     Positive claims only; "not gated" prose is not parsed.
#   C (WARN) every skill promoted by the cache's own plugin.json appears in
#     docs/reference/mattpocock-integration-map.md — routed from a kbg
#     surface or explicitly deferred — and the ledger's invocation column
#     (model/user) matches the installed frontmatter. Upstream adds or
#     renames a skill → this fails until kbg routes it or records why not.
#   D (INFO) a gated (user-invoke-only) matt skill cited in any live surface
#     except BOUNDARY.md (generated — regen inherits the source fixes) must
#     carry the literal slash form `/mattpocock-skills:<name>` on the same
#     line — docs/METHODOLOGY.md's "disable-model-invocation surfaces are user-only" rule: tell the user
#     the string to type; a bare ref reads as a model-invocable route and
#     the Skill call would be blocked mid-flow. Slash form only, no
#     free-text markers. INFO-only: the reader judges each finding.
#   E (INFO) a promoted skill's bare name — backtick-wrapped (`` `research` ``,
#     reads as a callable identifier) or a bare leading-slash form for a
#     user-tier skill (`/tdd`) — cited with NO `mattpocock-skills:` prefix.
#     Both resolve to nothing; A/B/C/D never see them because their own
#     extraction regex requires the `mattpocock-skills:` token to exist in
#     the first place (2026-08-31 gap: checks 37/46 only match `mh:` tokens,
#     leaving bare matt-skill names invisible to every existing check).
#     Excludes: README.md (mh's own context-frame section headers reuse
#     `research`/`triage` as frame names, not skill routes), docs/agents/*.md
#     (matt-owned, regenerated by setup-matt-pocock-skills — see its own
#     wayfinder:<type> label vocabulary, which reuses skill names as label
#     values), docs/reference/reasoning-models.md (a reasoning-pattern-label
#     table reusing skill names alongside first-principles/occams-razor),
#     BOUNDARY.md (generated — fix the generator, not the artifact).
#     Acceptance bar is "no NEW un-excluded finding," not zero globally —
#     semantic disambiguation of every remaining prose use is out of scope
#     for a grep-based check; document expected residual noise rather than
#     chase it (2026-08-31 review finding).
#   F (WARN) a ledger row whose touchpoint column (column 4 of a `|`-split
#     row — column 3 is invocation, already owned by C; reusing $3 here
#     would silently always-pass) starts "deferred" while a live surface
#     (excluding the ledger itself) already references
#     `mattpocock-skills:<name>` for that skill — ledger prose drifted from
#     reality (2026-08-30 audit found 3 such rows already stale at write
#     time). Fail-closed the same way C does: an empty promoted set warns
#     instead of silently passing.
# Historical names must be cited UNPREFIXED (plain `writing-great-skills`,
# no `mattpocock-skills:` namespace) so A stays a live-ref check — matching
# the former/removed convention checks 37/46 use for retired kbg names.
# Cache root resolution: scripts/_lib/mattpocock-root.sh's resolve_mattpocock_root
# (#92/T13 — shared with doctrine-bootstrap.sh's session preflight, replacing
# this check's own former ad-hoc version-scan). Override for tests:
# MH_MATT_CACHE. Missing/incomplete cache → INFO skip (an uninstalled
# companion plugin is doctrine-bootstrap.sh's warning to own — that session
# hook is the repo's informative-skip precedent, not check 25, which
# silently shrinks its known-skills set when the cache is absent).
_matt_display_base="${MH_MATT_CACHE:-$HOME/.claude/plugins/cache/mattpocock/mattpocock-skills}"
if ! resolve_mattpocock_root; then
  info "mattpocock-skills plugin cache not found or incomplete under ${_matt_display_base/#"$HOME"/\~} — sub-checks A-D skipped (companion plugin not installed/half-extracted; doctrine-bootstrap owns that warning)"
else
  _matt_ver="$MATT_VER"
  _mcache="$MATT_ROOT"
  # name → invocation tier ("user" when disable-model-invocation: true, else "model")
  declare -A _matt_inv=()
  while IFS= read -r _sf; do
    _sn=$(basename "$(dirname "$_sf")")
    if [ "$(fm_get "$_sf" "disable-model-invocation")" = "true" ]; then
      _matt_inv["$_sn"]="user"
    else
      _matt_inv["$_sn"]="model"
    fi
  done < <(find "$_mcache/skills" -name SKILL.md 2>/dev/null)

  # Promoted set from the cache's own plugin.json skills array — matt's repo
  # names it the authority on what ships ("./skills/<bucket>/<name>" paths,
  # leading "./" optional; last segment only, so a flattened tree parses
  # identically).
  _matt_promoted=()
  while IFS= read -r _pn; do
    [ -n "$_pn" ] && _matt_promoted+=("$_pn")
  done < <(grep -oE '"(\./)?skills/[^"]+"' "$_mcache/.claude-plugin/plugin.json" 2>/dev/null | sed 's/"//g; s|.*/||' | sort -u)
  # Fail-closed: an upstream plugin.json format change (object entries, an
  # absolute-path scheme, a renamed key) makes the regex above parse ZERO
  # promoted skills — and sub-check C would then pass vacuously, silent in
  # exactly the failure class this check exists to catch (adversarially
  # confirmed 2026-08-10). Cache ships SKILL.md files but the promoted set
  # parsed empty ⇒ the parser is blind, say so loudly.
  if [ "${#_matt_promoted[@]}" -eq 0 ] && [ "${#_matt_inv[@]}" -gt 0 ]; then
    warn "promoted-set parse yielded 0 skills from the $_matt_ver plugin.json while the cache ships ${#_matt_inv[@]} SKILL.md files — manifest format drifted; sub-check C is blind until this parser is updated (fail-closed)"
  fi

  # Live surfaces (A/B scope) — check 46's doc list + hooks/contexts/output-
  # styles. Excludes CHANGELOG + docs/research|post-mortems|plans (archival)
  # and skills/**/scripts (this check's own sources self-reference the token).
  _live55=()
  for _f in "$CLAUDE_DIR"/CLAUDE.md "$CLAUDE_DIR"/README.md "$CLAUDE_DIR"/BOUNDARY.md \
            "$CLAUDE_DIR"/agents/*.md \
            "$CLAUDE_DIR"/skills/*/*.md "$CLAUDE_DIR"/skills/*/*/*.md \
            "$CLAUDE_DIR"/hooks/**/*.sh "$CLAUDE_DIR"/hooks/hooks.json \
            "$CLAUDE_DIR"/output-styles/*.md "$CLAUDE_DIR"/contexts/*.md \
            "$CLAUDE_DIR"/docs/*.md "$CLAUDE_DIR"/docs/agents/*.md \
            "$CLAUDE_DIR"/docs/reference/*.md "$CLAUDE_DIR"/docs/skill-template/*.md; do
    [ -f "$_f" ] && _live55+=("$_f")
  done

  # A — refs resolve.
  for _f in "${_live55[@]}"; do
    while IFS= read -r _ref; do
      [ -n "$_ref" ] || continue
      _base="${_ref#mattpocock-skills:}"; _base="${_base##*/}"
      if [ -z "${_matt_inv[$_base]:-}" ]; then
        warn "dead mattpocock ref in ${_f#"$CLAUDE_DIR"/}: '$_ref' resolves to no skill in the installed cache ($_matt_ver) — upstream rename/removal; check matt's CHANGELOG"
      fi
    done < <(grep -hoE 'mattpocock-skills:[a-zA-Z0-9/_-]+' "$_f" 2>/dev/null | sort -u)
  done

  # B — flag claims match frontmatter. One finding per (file line × skill);
  # a multi-skill line asserts the flag about every skill it names — accepted
  # over-reach for a WARN a human reviews.
  for _f in "${_live55[@]}"; do
    while IFS= read -r _line; do
      while IFS= read -r _ref; do
        [ -n "$_ref" ] || continue
        _base="${_ref#mattpocock-skills:}"; _base="${_base##*/}"
        [ -n "${_matt_inv[$_base]:-}" ] || continue  # dead ref: A already warned
        if [ "${_matt_inv[$_base]}" != "user" ]; then
          warn "stale flag claim in ${_f#"$CLAUDE_DIR"/}: line asserts disable-model-invocation:true about '$_base' but the installed $_matt_ver frontmatter carries no such flag"
        fi
      done < <(printf '%s' "$_line" | grep -oE 'mattpocock-skills:[a-zA-Z0-9/_-]+' | sort -u)
    done < <(grep -h 'disable-model-invocation: true' "$_f" 2>/dev/null | grep 'mattpocock-skills:')
  done

  # C — coverage ledger.
  # Known gap (logged 2026-08-10, deliberately unfixed): the row greps below
  # have no fenced-code awareness — an illustrative ```-wrapped example table
  # inside the ledger would satisfy C. The ledger is kbg-authored (self-spoof
  # only, not an attack surface); revisit if example tables ever appear there.
  _ledger="$CLAUDE_DIR/docs/reference/mattpocock-integration-map.md"
  if [ ! -f "$_ledger" ]; then
    warn "mattpocock integration ledger missing (docs/reference/mattpocock-integration-map.md): ${#_matt_promoted[@]} promoted skills unaccounted — route each from a kbg surface or record an explicit deferral"
  else
    for _pn in ${_matt_promoted[@]+"${_matt_promoted[@]}"}; do
      # `|| true` neutralises `set -e` propagation when grep finds zero
      # matches (the exact "no ledger row yet" state this loop exists to
      # WARN about, e.g. right after an upstream rename) — same idiom as
      # check 34's `triggers=$(... ) || true`. Confirmed 2026-08-30 by a
      # repo-wide sweep: check 56:223 carried the identical bug (fixed
      # alongside this one); check 35:45's same-shape line is safe by
      # construction (its inner regex is a strict subset of the outer grep
      # that produced its input) and was left alone.
      _row=$(grep -E "^\|[[:space:]]*${_pn}[[:space:]]*\|" "$_ledger" 2>/dev/null | head -1) || true
      if [ -z "$_row" ]; then
        warn "ledger row missing for promoted matt skill '$_pn' — add a kbg route or an explicit deferral to docs/reference/mattpocock-integration-map.md"
        continue
      fi
      _col=$(printf '%s' "$_row" | awk -F'|' '{gsub(/^[ \t]+|[ \t]+$/,"",$3); print $3}')
      if [ "$_col" != "${_matt_inv[$_pn]:-}" ]; then
        warn "ledger invocation drift for '$_pn': ledger says '${_col}', installed $_matt_ver frontmatter says '${_matt_inv[$_pn]:-missing}' — upstream flipped the flag"
      fi
    done
    while IFS= read -r _rn; do
      [ -n "$_rn" ] || continue
      case "$_rn" in skill) continue ;; esac  # header row
      if [ -z "${_matt_inv[$_rn]:-}" ]; then
        warn "ledger row '$_rn' names a skill absent from the installed cache ($_matt_ver) — upstream removal/rename; update the ledger"
      fi
    done < <(awk -F'|' '/^\|/ {gsub(/^[ \t]+|[ \t]+$/,"",$2); print $2}' "$_ledger" 2>/dev/null | grep -vE '^-+$|^$')
    # Duplicate rows: the promoted-skill lookup above is head -1 first-match-
    # wins, so a second (possibly stale) row for the same skill is invisible
    # to the invocation-drift check (adversarially confirmed 2026-08-10).
    while IFS= read -r _dup; do
      [ -n "$_dup" ] || continue
      warn "ledger has duplicate rows for '$_dup' — only the first is checked; merge them (a stale duplicate is invisible to the invocation-drift check)"
    done < <(awk -F'|' '/^\|/ {gsub(/^[ \t]+|[ \t]+$/,"",$2); print $2}' "$_ledger" 2>/dev/null | grep -vE '^-+$|^$|^skill$' | sort | uniq -d)
  fi

  # D — gated-ref phrasing. Same live-surface scope as A/B minus BOUNDARY.md
  # (generated by skills/inventory/scripts/inventory-boundary.sh — its rows
  # mirror command/hook descriptions, so flagging it would double-count the
  # source; regen after fixing the source and it follows).
  _routing55=()
  for _f in "${_live55[@]}"; do
    case "$_f" in */BOUNDARY.md) continue ;; esac
    _routing55+=("$_f")
  done
  for _f in "${_routing55[@]}"; do
    while IFS= read -r _numline; do
      _ln="${_numline%%:*}"; _line="${_numline#*:}"
      while IFS= read -r _ref; do
        [ -n "$_ref" ] || continue
        _base="${_ref#mattpocock-skills:}"; _base="${_base##*/}"
        [ "${_matt_inv[$_base]:-}" = "user" ] || continue
        # Slash form ONLY — free-text fallback markers (type/user-invoked/
        # yourself) were droppable by any unrelated same-line use of those
        # words (adversarially confirmed 2026-08-10: "the user-only prototype
        # for <gated>" suppressed a real finding); the literal string the
        # user must type is the one marker coincidence can't fake.
        case "$_line" in
          *"/mattpocock-skills:$_base"*) continue ;;
        esac
        info "gated matt skill '$_base' cited without its slash form in ${_f#"$CLAUDE_DIR"/}:$_ln — disable-model-invocation:true upstream; cite the literal /mattpocock-skills:$_base on the same line (docs/METHODOLOGY.md's disable-model-invocation rule)"
      done < <(printf '%s' "$_line" | grep -oE 'mattpocock-skills:[a-zA-Z0-9/_-]+' | sort -u)
    done < <(grep -n 'mattpocock-skills:' "$_f" 2>/dev/null)
  done

  # E — bare (unnamespaced) matt-skill name references. Two shapes: a
  # backtick-wrapped promoted-skill name with no mattpocock-skills: prefix
  # inside the backticks (reads as a callable identifier — the wrong-when-
  # bare case), and a bare leading-slash form for a user-tier skill (the
  # correct form always has the slash BEFORE mattpocock-skills:, so a
  # correctly-namespaced /mattpocock-skills:<name> never matches "/<name>").
  _promoted_alt=$(printf '%s\n' "${_matt_promoted[@]}" | paste -sd'|' -)
  _user_alt=""
  for _pn in ${_matt_promoted[@]+"${_matt_promoted[@]}"}; do
    [ "${_matt_inv[$_pn]:-}" = "user" ] || continue
    _user_alt="${_user_alt:+$_user_alt|}$_pn"
  done
  if [ -n "$_promoted_alt" ]; then
    for _f in "${_live55[@]}"; do
      case "$_f" in
        */README.md|*/docs/agents/*.md|*/docs/reference/reasoning-models.md|*/BOUNDARY.md) continue ;;
      esac
      while IFS=: read -r _ln _match; do
        [ -n "$_match" ] || continue
        info "bare backtick matt-skill reference in ${_f#"$CLAUDE_DIR"/}:$_ln: $_match — not namespaced (mattpocock-skills:<name>), resolves to nothing as a callable identifier"
      done < <(grep -noE "\`($_promoted_alt)\`" "$_f" 2>/dev/null)
      if [ -n "$_user_alt" ]; then
        while IFS=: read -r _ln _match; do
          [ -n "$_match" ] || continue
          info "bare slash matt-skill reference in ${_f#"$CLAUDE_DIR"/}:$_ln: $_match — resolves to nothing; user-tier skills need the literal /mattpocock-skills:<name> form"
        done < <(grep -noE "/($_user_alt)\b" "$_f" 2>/dev/null)
      fi
    done
  fi

  # F — ledger prose drift: a "deferred" row whose skill is already
  # referenced elsewhere. Build the referenced-skill set with the same
  # extraction regex sub-check A already uses, so F only trusts what A
  # itself would also resolve.
  declare -A _referenced_matt=()
  for _f in "${_live55[@]}"; do
    case "$_f" in */mattpocock-integration-map.md) continue ;; esac
    while IFS= read -r _ref; do
      [ -n "$_ref" ] || continue
      _base="${_ref#mattpocock-skills:}"; _base="${_base##*/}"
      _referenced_matt["$_base"]=1
    done < <(grep -hoE 'mattpocock-skills:[a-zA-Z0-9/_-]+' "$_f" 2>/dev/null)
  done
  if [ -f "$_ledger" ]; then
    if [ "${#_matt_promoted[@]}" -eq 0 ]; then
      warn "sub-check F: promoted-set parsed empty — same fail-closed condition as C; F is blind until the plugin.json parser is updated"
    else
      for _pn in "${_matt_promoted[@]}"; do
        _row=$(grep -E "^\|[[:space:]]*${_pn}[[:space:]]*\|" "$_ledger" 2>/dev/null | head -1) || true
        [ -n "$_row" ] || continue  # C already warns on a missing row
        _touch=$(printf '%s' "$_row" | awk -F'|' '{gsub(/^[ \t]+|[ \t]+$/,"",$4); print $4}')
        case "$_touch" in
          deferred*)
            if [ -n "${_referenced_matt[$_pn]:-}" ]; then
              warn "ledger prose drift for '$_pn': row says 'deferred' but a live surface already references mattpocock-skills:$_pn — update the ledger row to 'routed' with the real touchpoint"
            fi
            ;;
        esac
      done
    fi
  fi

  unset _mcache _ledger _row _col _touch _pn _rn _sf _sn _live55 _routing55 _numline _ln _line _match _ref _base _matt_inv _matt_promoted _promoted_alt _user_alt _referenced_matt
fi
unset _matt_display_base _matt_ver _f MATT_ROOT MATT_VER
